export const PARA_STAGES = ["idea", "incubating", "active", "done"] as const;
export type ParaStage = (typeof PARA_STAGES)[number];
export type ParaBrief = {
  goal: string;
  success: string;
  constraints: string;
  decisions: string;
  questions: string;
  next: string;
};
export type ParaBoard = {
  id: string;
  user_id: string;
  name: string;
  position: number;
  default_project_id: string | null;
  revision: number;
  archived_at: string | null;
  created_at: string;
  updated_at: string;
};
export type ParaArea = {
  id: string;
  board_id: string;
  user_id: string;
  title: string;
  body: string;
  revision: number;
  archived_at: string | null;
  updated_at: string;
};
export type ParaSidebarProject = Pick<ParaProject, "id" | "board_id" | "title" | "stage" | "paused" | "revision" | "archived_at">;
export type ParaSidebarBoard = ParaBoard & { project_count: number };
export type ParaProject = {
  id: string;
  user_id: string;
  board_id: string;
  title: string;
  stage: ParaStage;
  paused: number;
  area_id: string | null;
  brief: ParaBrief;
  default_project_id: string | null;
  position: number;
  revision: number;
  archived_at: string | null;
  created_at: string;
  updated_at: string;
  resource_count?: number;
  conversation_count?: number;
  unread_count?: number;
  running_count?: number;
  wake_count?: number;
};
export type ParaResource = {
  id: string;
  user_id: string;
  board_id: string;
  area_id: string | null;
  title: string;
  kind: "note" | "link" | "file" | "excerpt";
  body: string;
  url: string;
  file_name: string | null;
  mime_type: string | null;
  size: number;
  sha256: string | null;
  source_conversation_id: string | null;
  source_message_id: string | null;
  source_file_id: string | null;
  source_title: string | null;
  revision: number;
  archived_at: string | null;
  created_at: string;
  updated_at: string;
  is_output?: number;
  pinned?: number;
};
export type ParaConversation = {
  id: string;
  title: string;
  project_id: string | null;
  project_name: string | null;
  executor_id: string | null;
  relation: "primary" | "reference";
  status: string;
  external_status: string;
  has_unread_result: number;
  active_wake_count: number;
  cold_storage_state: string;
  updated_at: string;
  main_title: string | null;
};
export type ParaDetail = {
  project: ParaProject;
  resources: ParaResource[];
  conversations: ParaConversation[];
  events: {
    id: number;
    action: string;
    revision: number;
    created_at: string;
  }[];
};
